# -*- coding: utf-8 -*-
"""Practica1VA-POO.ipynb
@author: chris-bena
@author: sourius
Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1X7Q9-V0gNq45HnNSwokQbB1zl5F9qEwc
"""

import cv2
import numpy as np
import matplotlib.pyplot as plt
from random import random
from colorsys import hsv_to_rgb
import os
from TSDetector import TSDetector
from MSERDetector import MSERDetector
import Constants

# probar que todo funciona correctamente
detector = TSDetector(Constants.DIM_X, Constants.DIM_Y, 0.5)
# inicializar mser
# delta 5, variation 1, area 2000
delta = Constants.MSER_DELTA
variation = Constants.MSER_VARIATION
area = Constants.MSER_MIN_AREA
detector.setMSER(delta, variation, area)

# inicializar mascaras medias
kernel = cv2.getStructuringElement(cv2.MORPH_RECT, Constants.KERNEL_SIZE)
detector.setMasks(kernel)

# generar mascaras medias
detector.generateAverageMasks("entradas.txt")
detector.detectar_señales_directorio('test')

